[package]
name = "yatd"
version = "0.1.0"
edition = "2021"
description = "Todo tracker for AI agents"

[[bin]]
name = "td"
path = "src/main.rs"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4", features = ["derive"] }
comfy-table = "7.2.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
loro = "1"
ulid = "1"
magic-wormhole = "0.7.6"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
